server:
  port: 9900

spring:
  application:
    name: thymeleaf

  thymeleaf: # https://blog.csdn.net/ice_lemon_g/article/details/73609020
    cache: false # 是否启用模板缓存（开发时建议关闭）
    mode: HTML5 # 应用于模板的模板模式
    ### 以下配置项皆可省略，采用默认即可 ###
    check-template: true # 检查模板是否存在，然后再呈现
    check-template-location: true # 检查模板位置是否存在
    servlet:
      content-type: text/html # Content-Type值
    enabled: true # 启用 MVC Thymeleaf 视图分辨率
    encoding: UTF-8 # 模板编码
    prefix: classpath:/templates/ # 在构建URL时预先查看名称的前缀
    suffix: .html # 在构建URL时附加查看名称的后缀


