application:
  name: prod环境 @artifactId@
  version: prod环境 @version@
developer:
  name: prod环境 dengjiaaa
  website: prod环境 http://dengjia.top/
  qq: prod环境 2663239386
  phone-number: prod环境 18402894534
